name: CI
on: [push]
jobs:
  install-web-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Node Environment
        uses: actions/setup-node@v2

      - name: Install hello-wordl vue app dependencies
        working-directory: ./hello-world
        run: npm install

      - name: install cypress environment dependencies
        working-directory: ./e2e
        run: npm install

      - name: Serve the app and run test  cypress
        run: |
          npm install
          npm run ci
