name: CI
on: [push]
jobs:
  install-web-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Node Environment
        uses: actions/setup-node@v2

      - name: install vue cli-service use for build
        working-directory: ./hello-world
        run: npm i @vue/cli-service
        
      - name: build hello-world
        working-directory: ./hello-world
        run: npm run build

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"

      - name: install cypress environment dependencies
        working-directory: ./e2e
        run: npm install

      - name: Serve the app and run test  cypress
        run: |
          npm install
          npm run ci-2
