name: CI
on: [push]
jobs:
  install-web-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Node Environment
        uses: actions/setup-node@v2

      - name: Install dependencies
        working-directory: ./hello-world
        run: |
          npm install

      - name: Create  cypress Environment
        working-directory: ./e2e
        run: |
          npm install
