name: main
on: [push]
jobs:
  run:
    name: RUN Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Node Environment
        uses: actions/setup-node@v2
      - name: run Node Environment
        run: |
          npm install
          npm run serve
        working-directory: ./hello-world
  test:
    name: TEST Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false
      - run: yarn lint
      - name: Run e2e tests
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          # Cypress tests and config file are in "e2e" folder
          working-directory: e2e