name: main
on: [push]
jobs:
  run:
    working-directory: hello-world # The working directory path
    name: RUN Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create Node Environment
        uses: actions/setup-node@master
      - name: Install MAIN Packages
        run: npm install -g @vue/cli yarn
      - name: Install hello world Packages and Build Application
        run: yarn install
      - name: run app ok
        run: yarn serve
