name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          working-directory: hello-world
          start: npm run serve
          wait-on: http://localhost:4700/
          config_file: cypress.json
          spec: "e2e/**/*"
        env:
          CYPRESS_baseUrl: http://localhost:4700/