name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
      - name: Install dependencies
        with:
          working-directory: hello-world
        run: npm install

      - name: Build
        with:
          working-directory: hello-world
        run: npm run build


      - name: Start server in the background
        run: npm start &

      # Cypress has its own package.json in folder "e2e"
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v1
        with:
          working-directory: e2e
