name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
        with:
          working-directory: hello-world
      - name: Install dependencies
        run: npm install
      - name: run
        run: npm run serve
